channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - r-base=4.3.2
  - r-lintr=3.1.1
  - r-ape=5.8
  - r-phytools=2.1.1
  - r-picante=1.8.2
  - r-RColorBrewer=1.1.3
  - r-ggplot2=3.5.1
  - r-dunn.test=1.3.5
  - r-caper=1.0.3
