channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - r-base=4.3.2
  - r-lintr=3.1.1
  - r-ape=5.8
  - r-phytools=2.1.1
  - r-picante=1.8.2
  - r-RColorBrewer=1.1.3
  - r-taxonomizr=0.7.1
  - r-taxizedb=0.3.1
  - r-packcircles=0.3.6
  - r-ggplot2=3.5.1
  - r-dunn.test=1.3.5
  - r-vioplot=0.5.0
  - r-caper=1.0.3
  - r-sm=2.2_5.4
  - r-rsqlite=2.3.7
