name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}

      - name: Lint root directory and children
        run: lintr::lint_dir(linters = lintr::with_defaults(object_usage_linter = NULL))
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
